blank_issues_enabled: false
contact_links:
  - name: Report a security vulnerability
    url: https://reactphp.org/#support
    about: 'If you discover a security vulnerability, please send us an email. Do not disclose security-related issues publicly.'
  - name: Feature request
    url: https://github.com/orgs/reactphp/discussions/categories/ideas
    about: 'You have ideas to improve our project? Start a new discussion in our "Ideas" category.'
  - name: Questions
    url: https://github.com/orgs/reactphp/discussions/categories/q-a
    about: 'We are happy to answer your questions! Start a new discussion in our "Q&A" category.'
